name: Citybuild
main: BlawoHD\Citybuild
api: 3.0.0
version: 0.3.0
author: BlawoHD
commands:
  fly:
    aliases: ["fliegen"]
    permission: "fly.use"
  heal:
    aliases: ["heilen"]
    permission: "heal.use"
  repair:
    aliases: [""]
    permission: "repair.use"
  repairall:
    aliases: [""]
    permission: "repairall.use"
  coins:
    aliases: ["geld", "money"]
    permission: "coins.use"
permissions:
  fly.use:
    default: op
  heal.use:
    default: op
  repair.use:
    default: op
  repairall.use:
    default: op
  coins.use:
    default: op