name: Citybuild
main: BlawoHD\Citybuild
api: 3.0.0
version: 0.1.3-BETA2
commands:
  fly:
    aliases: ["fliegen"]
    permission: "fly.use"
  heal:
    aliases: ["heilen"]
    permission: "heal.use"
  repair:
    aliases: ["reparieren"]
    permission: "repair.use"
  coins:
    aliases: ["geld", "money"]
    permission: "coins.use"
permissions:
  fly.use:
    default: op
  heal.use:
    default: op
  repair.use:
    default: op
  coins.use:
    default: op