name: Citybuild
main: BlawoHD\Citybuild
api: 3.0.0
version: 0.1.1-BETA1
commands:
  fly:
    aliases: ["fliegen"]
    permission: "fly.use"
  heal:
    aliases: ["heilen"]
    permission: "heal.use"
permissions:
  fly.use:
    default: op
  heal.use:
    default: op