name: Citybuild
main: BlawoHD\Citybuild
api: 3.0.0
version: 0.4.0
author: BlawoHD
commands:
  fly:
    aliases: ["fliegen"]
    permission: "fly.use"
  heal:
    aliases: ["heilen"]
    permission: "heal.use"
  feed:
    aliases: ["essen"]
    permission: "feed.use"
  size:
    aliases: ["groesse"]
    permission: "size.use"
  repair:
    aliases: [""]
    permission: "repair.use"
  repairall:
    aliases: [""]
    permission: "repairall.use"
  clear:
    aliases: [""]
    permission: "clear.use"
permissions:
  fly.use:
    default: op
  heal.use:
    default: op
  feed.use:
    default: op
  size.use:
    default: op
  repair.use:
    default: op
  repairall.use:
    default: op
  clear.use:
    default: op